# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='autor',
            name='ciudad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='autor',
            name='genero',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='libros',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.Categorias'),
        ),
        migrations.AlterField(
            model_name='libros',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
