# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_auto_20180601_1437'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorias',
            new_name='Categoria',
        ),
    ]
